### ISSUE TITLE
Enhancement to tailscale running in docker

### ISSUE THREAD

**Issue by baltazartroisville** [spotsnel/cockpit-tailscale#45]
Hello gbraad,

I propose an enhancement that would allow to support tailscale running in docker (and the same for cockpit-cloudflared as well). 
I think this would be a valuable addition for everybody. I mean, maybe you have that planned already or it is out of the scope for that project but i thought i might just ask.

I would like to thank you for the effort, dedication and work you have done already and im very impressed by your idea. 

With kind regards!

**Comment by gbraad** [comment]
I have containers for this already and the issue exists: #5.

Finding time to finish the work has been difficult as I am in the middle of moving and renovation.
